version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: logistica-maria
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: logistica_a
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  postgres:
    image: postgres:16
    container_name: logistica-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: logistica_b
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mariadb_data:
  postgres_data:
